# Generated by Django 4.2.2 on 2023-06-17 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('course', models.CharField(max_length=50)),
                ('tools', models.CharField(choices=[('flute', 'флейта'), ('violin', 'скрипка'), ('drums', 'баробаны'), ('guitarac', 'гитара')], max_length=30)),
                ('academic_performance', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.BooleanField()),
            ],
        ),
    ]
