# Generated by Django 5.0.1 on 2024-01-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiciant', '0002_alter_student_academic_performance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tools',
            field=models.CharField(choices=[('guitarac', 'guitar'), ('drums', 'drum'), ('violin', 'violin'), ('flute', 'flute')], max_length=30),
        ),
    ]
